# Generated by Django 6.0.2 on 2026-02-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth0_sub',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
